#!/usr/bin/env bash

set -e

WALL="$1"

if [ -z "$WALL" ]; then
    WALL=$(find "$HOME/Projects/dotfiles/wallpapers" -type f | shuf -n1)
fi

pgrep swww-daemon >/dev/null || swww-daemon

swww img "$WALL" \
    --transition-type grow \
    --transition-pos 0.5,0.5 \
    --transition-duration 0.8

# Тут потім буде:
# matugen image "$WALL"
# ~/.config/waybar/reload.sh
# makoctl reload